name: Check-Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Restore and build (publish)
        run: dotnet publish --configuration Release /p:PublishProfile=plugin_owoTrackVR\Properties\PublishProfiles\FolderProfile.pubxml
        
      - name: Pack published files
        run: |
          cd plugin_owoTrackVR/bin/Release/net8.0/win-x64/publish
          7z a plugin_owoTrackVR.zip *
        
      - name: Upload plugin artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "plugin_owoTrackVR Build Artifact"
          files: |
            ./plugin_owoTrackVR/bin/Release/net8.0/win-x64/publish/plugin_owoTrackVR.zip
            ./external/manifest.json